[2020-06-03 18:39:00,916] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.second_task 2020-06-03T13:06:58.113610+00:00 [queued]>
[2020-06-03 18:39:00,926] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.second_task 2020-06-03T13:06:58.113610+00:00 [queued]>
[2020-06-03 18:39:00,926] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:39:00,926] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-03 18:39:00,926] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:39:00,934] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): second_task> on 2020-06-03T13:06:58.113610+00:00
[2020-06-03 18:39:00,937] {standard_task_runner.py:53} INFO - Started process 19235 to run task
[2020-06-03 18:39:00,977] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: hello_world.second_task 2020-06-03T13:06:58.113610+00:00 [running]> shreya-nineleaps
[2020-06-03 18:39:00,992] {logging_mixin.py:112} INFO - Unnamed: 0     int64
states        object
cases          int64
date          object
dtype: object
[2020-06-03 18:39:03,633] {taskinstance.py:1145} ERROR - Please verify that the structure and data types in the DataFrame match the schema of the destination table.
Traceback (most recent call last):
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/hello_world.py", line 41, in second_function
    table_schema=None)
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 1523, in to_gbq
    private_key=private_key,
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas/io/gbq.py", line 209, in to_gbq
    private_key=private_key,
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 1178, in to_gbq
    "Please verify that the structure and "
pandas_gbq.gbq.InvalidSchema: Please verify that the structure and data types in the DataFrame match the schema of the destination table.
[2020-06-03 18:39:03,637] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=hello_world, task_id=second_task, execution_date=20200603T130658, start_date=20200603T130900, end_date=20200603T130903
[2020-06-03 18:39:10,907] {logging_mixin.py:112} INFO - [2020-06-03 18:39:10,906] {local_task_job.py:103} INFO - Task exited with return code 1
