[2020-06-03 16:18:50,661] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2020-06-03T10:47:04.920121+00:00 [queued]>
[2020-06-03 16:18:50,671] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.hello_task 2020-06-03T10:47:04.920121+00:00 [queued]>
[2020-06-03 16:18:50,671] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 16:18:50,671] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-03 16:18:50,671] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 16:18:50,680] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): hello_task> on 2020-06-03T10:47:04.920121+00:00
[2020-06-03 16:18:50,682] {standard_task_runner.py:53} INFO - Started process 9406 to run task
[2020-06-03 16:18:50,722] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: hello_world.hello_task 2020-06-03T10:47:04.920121+00:00 [running]> shreya-nineleaps
[2020-06-03 16:18:52,592] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: 'home/nineleaps/Documents/csv/csv_03-06-2020.csv'
Traceback (most recent call last):
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/hello_world.py", line 25, in print_hello
    dff.to_csv(csv_name)
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3228, in to_csv
    formatter.save()
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 183, in save
    compression=self.compression,
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 399, in _get_handle
    f = open(path_or_buf, mode, encoding=encoding, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'home/nineleaps/Documents/csv/csv_03-06-2020.csv'
[2020-06-03 16:18:52,599] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=hello_world, task_id=hello_task, execution_date=20200603T104704, start_date=20200603T104850, end_date=20200603T104852
[2020-06-03 16:19:00,646] {logging_mixin.py:112} INFO - [2020-06-03 16:19:00,645] {local_task_job.py:103} INFO - Task exited with return code 1
